project:
  type: website
  output-dir: "."

website:
  title: "Home"
  navbar:
    right:
      - text: "Resume"
        href: resume.html
      - icon: envelope
        href: mailto:<sns2189@cumc.columbia.edu>
      - icon: github
        href: http://github.com/safiyasirota/
      - icon: linkedin
        href: https://www.linkedin.com/in/safiya-sirota/

format:
  html:
    theme: darkly
    fontcolor: "white"
    mainfont: "Courier New"
    linkcolor: "pink"
    css: styles.css
    toc: false